# Evaluation Metrics Playground

In [8]:
import torch
from torchmetrics import *
from pprint import pprint
from utils.auprc import AUPRC

Create a toy batch

In [9]:
pred = torch.stack([torch.tensor([
    [1, 0.8, 0.6, 0.5, 0.4],
    [0, 0, 0.4, 0.2, 0.3],
    [0, 0.2, 0, 0.3, 0.3]
]), torch.tensor([
    [0.1, 0.1, 0.3, 0.1, 0.3],
    [0.9, 0.5, 0.4, 0, 0.3],
    [0, 0.4, 0.3, 0.9, 0.4]
], dtype=torch.float)])

target = torch.stack([torch.tensor(
    [0, 0, 0, 0, 0]
), torch.tensor(
    [1, 1, 1, 2, 2]
)])

Inspect metrics results

In [14]:
metrics = MetricCollection(
    Accuracy(num_classes=3,
             compute_on_step=False),
    F1(num_classes=3,
       average="macro",
       mdmc_average="global",
       compute_on_step=False),
    ConfusionMatrix(num_classes=3,
                    compute_on_step=False),
    PrecisionRecallCurve(num_classes=3)
)
metrics(pred, target)
result = metrics.compute()
pprint(result)

{'Accuracy': tensor(1.),
 'ConfusionMatrix': tensor([[5., 0., 0.],
        [0., 3., 0.],
        [0., 0., 2.]]),
 'F1': tensor(1.),
 'PrecisionRecallCurve': ([tensor([1., 1., 1., 1., 1., 1.]),
                           tensor([0.7500, 1.0000, 1.0000, 1.0000]),
                           tensor([0.6667, 1.0000, 1.0000])],
                          [tensor([1.0000, 0.8000, 0.6000, 0.4000, 0.2000, 0.0000]),
                           tensor([1.0000, 0.6667, 0.3333, 0.0000]),
                           tensor([1.0000, 0.5000, 0.0000])],
                          [tensor([0.4000, 0.5000, 0.6000, 0.8000, 1.0000]),
                           tensor([0.4000, 0.5000, 0.9000]),
                           tensor([0.4000, 0.9000])])}
